import requests


# self-defined libraries
# from Hash_countrycode import convert_to_countrycode

countries = {'Andorra': 'AD', 
             'United Arab Emirates': 'AE', 
             'Afghanistan': 'AF', 
             'Antigua and Barbuda': 'AG', 
             'Anguilla': 'AI', 
             'Albania': 'AL', 
             'Armenia': 'AM', 
             'Angola': 'AO', 
             'Argentina': 'AR', 
             'American Samoa': 'AS', 
             'Austria': 'AT', 
             'Australia': 'AU', 
             'Aruba': 'AW', 
             'Azerbaijan': 'AZ', 
             'Bosnia and Herzegovina': 'BA', 
             'Barbados': 'BB', 
             'Bangladesh': 'BD', 
             'Belgium': 'BE', 
             'Burkina Faso': 'BF', 
             'Bulgaria': 'BG', 
             'Bahrain': 'BH', 
             'Burundi': 'BI', 
             'Benin': 'BJ', 
             'Saint Barthelemy': 'BL', 
             'Bermuda': 'BM', 
             'Brunei': 'BN', 
             'Bolivia': 'BO',
             'Brazil': 'BR', 
             'Bahamas, The': 'BS', 
             'Bhutan': 'BT', 
             'Botswana': 'BW', 
             'Belarus': 'BY', 
             'Belize': 'BZ', 
             'Canada': 'CA', 
             'Cocos (Keeling) Islands': 'CC', 
             'Congo (Kinshasa)': 'CD', 
             'Central African Republic': 'CF', 
             'Congo (Brazzaville)': 'CG', 
             'Switzerland': 'CH', 
             'Côte d’Ivoire': 'CI', 
             'Cook Islands': 'CK', 
             'Chile': 'CL', 
             'Cameroon': 'CM', 
             'China': 'CN', 
             'Colombia': 'CO', 
             'Costa Rica': 'CR', 
             'Cuba': 'CU', 
             'Cabo Verde': 'CV',
             'Christmas Island': 'CX', 
             'Cyprus': 'CY', 
             'Czechia': 'CZ', 
             'Germany': 'DE', 
             'Djibouti': 'DJ', 
             'Denmark': 'DK', 
             'Dominica': 'DM', 
             'Dominican Republic': 'DO', 
             'Algeria': 'DZ', 
             'Ecuador': 'EC', 
             'Estonia': 'EE', 
             'Egypt': 'EG', 
             'Western Sahara': 'EH', 
             'Eritrea': 'ER', 
             'Spain': 'ES', 
             'Ethiopia': 'ET', 
             'Finland': 'FI', 
             'Fiji': 'FJ', 
             'Falkland Islands': 'FK', 
             'Micronesia, Federated States of': 'FM', 
             'Faroe Islands': 'FO', 
             'France': 'FR', 
             'Gabon': 'GA', 
             'United Kingdom': 'GB', 
             'Grenada': 'GD', 
             'Georgia': 'GE', 
             'French Guiana': 'GF', 
             'Guernsey': 'GG', 
             'Ghana': 'GH', 
             'Gibraltar': 'GI', 
             'Greenland': 'GL', 
             'Gambia, The': 'GM', 
             'Guinea': 'GN', 
             'Guadeloupe': 'GP', 
             'Equatorial Guinea': 'GQ', 
             'Greece': 'GR', 
             'South Georgia and South Sandwich Islands': 'GS', 
             'Guatemala': 'GT', 
             'Guam': 'GU', 
             'Guinea-Bissau': 'GW', 
             'Guyana': 'GY', 
             'Hong Kong': 'HK', 
             'Honduras': 'HN', 
             'Croatia': 'HR', 
             'Haiti': 'HT', 
             'Hungary': 'HU', 
             'Indonesia': 'ID', 
             'Ireland': 'IE', 
             'Israel': 'IL', 
             'Isle of Man': 'IM', 
             'India': 'IN', 
             'Iraq': 'IQ', 
             'Iran': 'IR', 
             'Iceland': 'IS', 
             'Italy': 'IT', 
             'Jersey': 'JE', 
             'Jamaica': 'JM', 
             'Jordan': 'JO', 
             'Japan': 'JP', 
             'Kenya': 'KE', 
             'Kyrgyzstan': 'KG', 
             'Cambodia': 'KH',
             'Kiribati': 'KI', 
             'Comoros': 'KM', 
             'Saint Kitts and Nevis': 'KN', 
             'Korea, North': 'KP', 
             'Korea, South': 'KR', 
             'Kuwait': 'KW', 
             'Cayman Islands': 'KY', 
             'Kazakhstan': 'KZ', 
             'Laos': 'LA', 
             'Lebanon': 'LB', 
             'Saint Lucia': 'LC', 
             'Liechtenstein': 'LI', 
             'Sri Lanka': 'LK', 
             'Liberia': 'LR', 
             'Lesotho': 'LS', 
             'Lithuania': 'LT', 
             'Luxembourg': 'LU', 
             'Latvia': 'LV', 
             'Libya': 'LY', 
             'Morocco': 'MA', 
             'Monaco': 'MC', 
             'Moldova': 'MD', 
             'Montenegro': 'ME', 
             'Saint Martin': 'MF', 
             'Madagascar': 'MG', 
             'Marshall Islands': 'MH', 
             'North Macedonia': 'MK', 
             'Mali': 'ML', 
             'Myanmar': 'MM', 
             'Mongolia': 'MN', 
             'Macau': 'MO', 
             'Northern Mariana Islands': 'MP', 
             'Martinique': 'MQ', 
             'Mauritania': 'MR', 
             'Montserrat': 'MS', 
             'Malta': 'MT', 
             'Mauritius': 'MU', 
             'Maldives': 'MV', 
             'Malawi': 'MW', 
             'Mexico': 'MX', 
             'Malaysia': 'MY', 
             'Mozambique': 'MZ', 
             'Namibia': 'NA', 
             'New Caledonia': 'NC', 
             'Niger': 'NE', 
             'Norfolk Island': 'NF', 
             'Nigeria': 'NG', 
             'Nicaragua': 'NI', 
             'Netherlands': 'NL', 
             'Norway': 'NO', 
             'Nepal': 'NP', 
             'Niue': 'NU', 
             'New Zealand': 'NZ', 
             'Oman': 'OM', 
             'Panama': 'PA', 
             'Peru': 'PE', 
             'French Polynesia': 'PF', 
             'Papua New Guinea': 'PG', 
             'Philippines': 'PH', 
             'Pakistan': 'PK', 
             'Poland': 'PL', 
             'Saint Pierre and Miquelon': 'PM', 
             'Pitcairn Islands': 'PN', 
             'Puerto Rico': 'PR', 
             'Palestinian Territory': 'PS', 
             'Portugal': 'PT', 
             'Palau': 'PW', 
             'Paraguay': 'PY', 
             'Qatar': 'QA', 
             'Reunion': 'RE', 
             'Romania': 'RO', 
             'Serbia': 'RS', 
             'Russia': 'RU', 
             'Rwanda': 'RW', 
             'Saudi Arabia': 'SA', 
             'Solomon Islands': 'SB', 
             'Seychelles': 'SC', 
             'Sudan': 'SD', 
             'Sweden': 'SE', 
             'Singapore': 'SG', 
             'Saint Helena, Ascension, and Tristan da Cunha': 'SH', 
             'Slovenia': 'SI', 
             'Svalbard and Jan Mayen': 'SJ', 
             'Slovakia': 'SK', 
             'Sierra Leone': 'SL', 
             'San Marino': 'SM', 
             'Senegal': 'SN', 
             'Somalia': 'SO', 
             'Suriname': 'SR', 
             'South Sudan': 'SS', 
             'Sao Tome and Principe': 'ST', 
             'El Salvador': 'SV', 
             'Sint Maarten': 'SX',
             'Syria': 'SY', 
             'Swaziland': 'SZ', 
             'Turks and Caicos Islands': 'TC', 
             'Chad': 'TD', 
             'Togo': 'TG', 
             'Thailand': 'TH', 
             'Tajikistan': 'TJ', 
             'Timor-Leste': 'TL', 
             'Turkmenistan': 'TM', 
             'Tunisia': 'TN', 
             'Tonga': 'TO', 
             'Turkey': 'TR', 
             'Trinidad and Tobago': 'TT', 
             'Tuvalu': 'TV', 
             'Taiwan': 'TW', 
             'Tanzania': 'TZ', 
             'Ukraine': 'UA', 
             'Uganda': 'UG', 
             'United States': 'US', 
             'Uruguay': 'UY', 
             'Uzbekistan': 'UZ', 
             'Vatican City': 'VA', 
             'Saint Vincent and the Grenadines': 'VC', 
             'Venezuela': 'VE', 
             'Virgin Islands, British': 'VG', 
             'U.S. Virgin Islands': 'VI', 
             'Vietnam': 'VN', 
             'Vanuatu': 'VU', 
             'Wallis and Futuna': 'WF', 
             'Samoa': 'WS', 
             'Kosovo': 'XK', 
             'Yemen': 'YE', 
             'Mayotte': 'YT', 
             'South Africa': 'ZA', 
             'Zambia': 'ZM', 
             'Zimbabwe': 'ZW'}

def convert_to_countrycode(country_name: str):
    return countries.get(country_name)


# function to check if it is safe to travel or not
def check_safety(country):
    # note that not all countries are accessible
    countrycode = convert_to_countrycode(country.title())

    # if it doesnt exists in travel advisory db, assume no data = safe
    if countrycode == None:
        return ("safe", "")

    travel_advisory_url = "https://www.travel-advisory.info/api?countrycode={}".format(countrycode)
    response = requests.get(travel_advisory_url)

    # Process the JSON data
    if response.status_code == 200:
        json_data = response.json()
        safety_index = json_data["data"][countrycode]["advisory"]["score"]
        # safety_msg = json_data["data"][countrycode]["advisory"]["message"]
        safety_msg = "{} has a current risk level of {} (out of 5). It is not safe to travel.".format(country, safety_index, country)
        if safety_index >= 3.5:
            return (safety_index, safety_msg)
        else:
            return ("safe", "")
    else:
        print(f"Error fetching data (status code {response.status_code})")
        return("error", f"Error fetching data (status code {response.status_code})")


            

#############################################################
# print(check_safety("United Kingdom"))
# print(check_safety("Afghanistan"))


# This function returns:
# (safe, "") or (unsafe, "<message of why is it unsafe>")

###
# risk value of 4.5-5: Avoid any trips
# risk value of 3.5-4.5: Reduce travel to bare minimum, conduct any travels with good preparation and high attention
# risk value of 2.5-3.5: Warnings relate to specific regions of the country, still advised to remain vigilant
# risk value of 0-2.5: Relatively safe
###
